services:
  server:
    build: "./Server/"
    ports:
      - "8000:8000"
    networks:
      - connection

  frontend:
    build: .
    ports:
      - "8080:80"
    networks:
      - connection
    depends_on:
      - server

networks:
  connection:
    driver: bridge